# Usage: bash collect_data.sh [--debug]   (--debug skips policy inference in ScriptRobot.teleop_step)
# DEBUG_ARG=""
# if [[ "$1" == "--debug" ]]; then
#     DEBUG_ARG="--robot.debug=true"
# fi

# pixi run python lerobot/scripts/control_robot.py --robot.type=script --robot.script_mode=pose --control.type=record --control.single_task="Pick toys" --control.repo_id=yinongh/adapt1 --control.num_episodes=1 --robot.cameras='{"cam_azure_kinect_left": {"type": "azurekinect", "device_id": 1, "fps": 30, "width": 1280, "height": 720, "use_transformed_depth": false, "wired_sync_mode": "master"}, "cam_azure_kinect_front": {"type": "azurekinect", "device_id": 0, "fps": 30, "width": 1280, "height": 720, "use_transformed_depth": false, "wired_sync_mode": "subordinate", "subordinate_delay_off_master_usec": 200}, "cam_wrist": {"type": "zed", "serial_number": "10296178", "fps": 30, "width": 1280, "height": 720, "use_depth": false}}' --robot.use_eef=true --control.push_to_hub=true --control.fps=30 --control.reset_time_s=5 --control.warmup_time_s=3 --control.num_image_writer_processes=4 --control.display_data=false --control.episode_time_s=180

# pixi run python lerobot/scripts/control_robot.py --robot.type=script --robot.script_mode=move_to_insertion --control.type=record --control.single_task="Single_Adapt" --control.repo_id=yinongh/adapt1 --control.num_episodes=33 --robot.cameras='{"cam_azure_kinect_front": {"type": "azurekinect", "device_id": 0, "fps": 30, "width": 1280, "height": 720, "use_transformed_depth": false}, "cam_wrist": {"type": "zed", "serial_number": "10296178", "fps": 30, "width": 1280, "height": 720, "use_depth": false}, "cam_auxiliary": {"type": "zed", "serial_number": "19112424", "fps": 30, "width": 1280, "height": 720, "use_depth": false}}' --robot.use_eef=true --control.push_to_hub=true --control.fps=30 --control.reset_time_s=5 --control.warmup_time_s=3 --control.num_image_writer_processes=4 --control.display_data=false --control.episode_time_s=1000 --control.resume=false

pixi run python lerobot/scripts/control_robot.py --robot.type=script --robot.script_mode=move_to_insertion --control.type=record --control.single_task="Single_Adapt" --control.repo_id=yinongh/adapt1 --control.num_episodes=33 --robot.cameras='{"cam_azure_kinect_front": {"type": "azurekinect", "device_id": 0, "fps": 30, "width": 1280, "height": 720, "use_transformed_depth": false}, "cam_wrist": {"type": "zed", "serial_number": "10296178", "fps": 30, "width": 1280, "height": 720, "use_depth": false}}' --robot.use_eef=true --control.push_to_hub=true --control.fps=30 --control.reset_time_s=5 --control.warmup_time_s=3 --control.num_image_writer_processes=4 --control.display_data=false --control.episode_time_s=1000 --control.resume=false $DEBUG_ARG --robot.debug=true

# rm -rf ~/.cache/huggingface/lerobot/yinongh/adapt1
